Added CreateBookRequestDto and BookDto, added BookMapper with MapperC…
YuraKhilko/book-store pull request #2
Opened 2023-08-09 17:00 UTC by YuraKhilko

…onfig, added BookController with methods public List<BookDto> getAll(), public BookDto getBookById(Long id), public BookDto createBook(CreateBookRequestDto bookDto), added EntityNotFoundException.

2023-08-09 17:45 UTC, aaananas approved these changes

2023-08-10 09:40 UTC, Rommelua requested changes

2023-08-10 09:40 UTC, Rommelua commented on pom.xml
> +                    <sourceDirectories>${project.build.sourceDirectory}</sourceDirectories>
What is this property value? /src/main/java? You should add test for checkstyle as well

2023-08-10 09:40 UTC, Rommelua commented on src/main/java/bookstore/model/Book.java
>  @Data
better do not use @Data with Entity class
@Getter
@Setter
@NoArgsConstructor - is good enough and you will control equals/hashCode/toString

2023-08-11 11:44 UTC, Rommelua approved these changes

2023-08-11 11:44 UTC, Rommelua commented on src/main/java/bookstore/dto/CreateBookRequestDto.java
> +    private Long id;
```suggestion
```

2023-08-11 11:50 UTC, merged